version: "3.3"
services:
  mqtt:
    image: ansi/mosquitto
    ports:
      - "1883:1883"
  nodered:
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - .\node_red_data:/data  
 
    
    
      
